# travis configuration
sudo: required
services:
  - docker

before_install:
  - docker build -t bendev2017/docker-react -f Dockerfile.dev .

script:
  - docker run bendev2017/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-2-2234fjed90j3d2"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  
